### ISSUE TITLE
Loading stuck at 95%

### ISSUE THREAD

**Issue by garridovaz** [arpitworld/Pivotal-Member-Tracker#1]
Since a couple of days, the loading bar gets stuck at 95% after I've added my API token and project ID. Everything worked fine previously.

**Comment by arpitworld** [comment]
Will look into it as soon as I find time.
Regards,
Arpit

**Comment by garridovaz** [comment]
Hi Arpit,

It’s working again, not sure what happened there. Thanks for replying.

-- 
Fernando Garrido Vaz
Product Manager

http://blog.garridovaz.com
@garrido

On February 9, 2015 at 16:25:48, Arpit Agrawal (notifications@github.com) wrote:

Will look into it as soon as I find time.
Regards,
Arpit

**Comment by arpitworld** [comment]
Awesome.
